import { Account, Simulation, Activity, Bill, Interest } from '../types/types';

export const makeAccount = (overrides: Partial<Account> = {}): Account => ({
  id: 'acc-1',
  name: 'Test Account',
  balance: 1000,
  hidden: false,
  type: 'Checking',
  pullPriority: 1,
  interestTaxRate: 0,
  withdrawalTaxRate: 0,
  earlyWithdrawalPenalty: 0,
  earlyWithdrawalDate: null,
  interestPayAccount: null,
  interestAppliesToPositiveBalance: false,
  usesRMD: false,
  accountOwnerDOB: null,
  rmdAccount: null,
  minimumBalance: null,
  minimumPullAmount: null,
  maximumBalance: null,
  performsPulls: false,
  performsPushes: false,
  pushStart: null,
  pushEnd: null,
  pushAccount: null,
  ...overrides,
});

export const makeSimulation = (overrides: Partial<Simulation> = {}): Simulation => ({
  name: 'Base Case',
  variables: {},
  enabled: true,
  selected: false,
  ...overrides,
});

export const makeActivity = (overrides: Partial<Activity> = {}): Activity => ({
  id: 'act-1',
  date: '2026-03-12',
  dateIsVariable: false,
  dateVariable: null,
  name: 'Test Activity',
  category: 'Groceries',
  amount: 100,
  flag: false,
  flagColor: null,
  amountIsVariable: false,
  amountVariable: null,
  isTransfer: false,
  from: null,
  to: null,
  billId: null,
  firstBill: false,
  interestId: null,
  firstInterest: false,
  spendingTrackerId: null,
  firstSpendingTracker: false,
  balance: 1000,
  cashBalance: 1000,
  investmentValue: 0,
  investmentActivityType: 'buy',
  investmentActions: [],
  ...overrides,
});

export const makeBill = (overrides: Partial<Bill> = {}): Bill => ({
  id: 'bill-1',
  startDate: '2026-03-01',
  startDateIsVariable: false,
  startDateVariable: null,
  endDate: null,
  endDateIsVariable: false,
  endDateVariable: null,
  everyN: 1,
  periods: 'month',
  isAutomatic: false,
  name: 'Test Bill',
  category: 'Utilities',
  amount: 150,
  flag: false,
  flagColor: null,
  amountIsVariable: false,
  amountVariable: null,
  isTransfer: false,
  from: null,
  to: null,
  annualStartDate: null,
  annualEndDate: null,
  annualStartDateIsVariable: false,
  annualEndDateIsVariable: false,
  annualStartDateVariable: null,
  annualEndDateVariable: null,
  increaseBy: 0.03,
  increaseByIsVariable: true,
  increaseByVariable: 'INFLATION',
  increaseByDate: '01/01',
  ...overrides,
});

export const makeInterest = (overrides: Partial<Interest> = {}): Interest => ({
  id: 'int-1',
  apr: 0.05,
  aprIsVariable: false,
  aprVariable: null,
  compounded: 'month',
  applicableDate: '2026-03-31',
  applicableDateIsVariable: false,
  applicableDateVariable: null,
  ...overrides,
});
